# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TTI-backend

on:
  push:
    branches:
      - cosmos
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_60b295b050064c02acc3b78f69f3d100 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_09c0f6957b954e639553aa2c23dc7d1d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_60b295b050064c02acc3b78f69f3d100 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TTI-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2374bba4d6e545549ae90ad6d0e498cb }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_60b295b050064c02acc3b78f69f3d100 }}/appsvc/staticsite:${{ github.sha }}'